<?php
namespace Drupal\test\Controller;
/**
 * @file
 * Contains test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\StringTranslation;

/**
 * Implements hook_help().
 */
function test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the test module.
    case 'help.page.test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module de test Backend') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_preprocess_hook()
 */
function test_perprocess_node(&$variables){

 if($variables['node']->id()== 1){
   $variables['content']['body'][0]['#text'] .= "oui c'est un text";
 }
}

/**
 * Implementing hook_theme()
 */

function drupal_controller_theme($existing,$type,$theme,$path){
return array(
  'article_List' => array(
    'variables' =>array(), 'title' => ''
  )
);
}
